### ISSUE TITLE
error message in tk_ts

### ISSUE THREAD

**Issue by jjesusfilho** [business-science/timetk#11] opened 2017-10-17 12:00 UTC
I get the following message when I call tk_ts() function:

tk_ts(select=roubo_veiculo,frequency=12,start=2003)

Error in tk_xts_.data.frame(ret, select = select, silent = silent) : 
  No date or date-time column found. Object must contain an unambigous date or date-time column

I thought that there was no need to specify a date column.

**Comment by mdancho84** [comment] 2017-10-25 14:47
Please provide a reproducible example. The date / datetime column in you data is not being detected for some reason, however I cannot reproduce your error.

**Comment by mdancho84** [comment] 2020-04-30 02:21
closing due to length of time open.

**Closed by mdancho84** 2020-04-30 02:21 UTC
