### ISSUE TITLE
Error in time_series_cv

### ISSUE THREAD

**Issue by aluxh** [business-science/timetk#33] opened 2020-04-29 12:08 UTC
Time Series Cross Validation returns an error, after successfully creating the CV object. The error received is 

`Error in `[.tbl_df`(x, is.finite(x <- as.numeric(x))) : 
  'list' object cannot be coerced to type 'double'`

This error is thrown when I was trying to look at the object via Console, and in View(), it shows empty object with only headers. However, I was able to access all the splits, using `analysis()` or `assessment()` methods. And, I can also use it for tuning.

**Comment by mdancho84** [comment] 2020-04-29 12:17
Is this error in the latest development version? 
Also, I don't see any code to reproduce the error. Providing a reproducible code will help in future troubleshooting.

**Comment by aluxh** [comment] 2020-05-09 01:59
Yes, it is the latest development version. Let me try if I can provide some code for that

**Comment by mdancho84** [comment] 2020-06-01 11:38
Hi Alex, 
I'm closing this issue due to time open. If the issues persists, we can reopen. 
-Matt

**Closed by mdancho84** 2020-06-01 11:38 UTC
