### ISSUE TITLE
tk_make_future_timeseries unable to handle months ending in 31

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [business-science/timetk#72] opened 2021-01-23 18:18 UTC
Hi Matt,

I was working with a quarterly time series whose index we can reconstruct from as follows:

`index <- timetk::tk_make_timeseries(start_date = '2011-09-30', end_date = '2018-12-31', by = 'quarter')`

`real_index<-dplyr::case_when(month(index) == 3 ~ index %+time% "1 day",
                             month(index) == 6 ~ index,
                             month(index) == 9 ~ index,
                             month(index) == 12 ~ index %+time% "1 day")`

The difference between the first index ("index") and the second ("real index") is that in the second the months of March and December have 31 days while in the first case (generated by tk_make_timeseries) all the months have 30 days.

If we try to lengthen the series with tk_make_future_timeseries with the first index, we don't get any problem. 
If we do it with the second index, we get the following error:

`real_index %>% timetk::tk_make_future_timeseries(length_out = "3 years")`

Error in validObject(.Object) : 
  invalid class “Period” object: periods must have integer values

This is a known issue as can be seen here: https://github.com/tidyverse/lubridate/issues/863

but I was wondering if the function could be adapted to take this into account and somehow make the calculation correctly, or, if on the contrary it is necessary for users to adapt our indexes from index 2 ("real_index") to index 1 ( "index").

Thanks, and big congrats for this great package!

**Comment by mdancho84** [comment] 2021-01-23 18:37
Thanks for this. I will take a look soon.

**Comment by mdancho84** [comment] 2021-02-18 20:30
Something I'm following is the `clock` package that may make this type of low-level calculation more transparent and better. https://github.com/r-lib/clock/

**Comment by AlbertoAlmuinha** [comment] 2021-03-19 19:06
Hi @mdancho84 , 

I would like to insist on this if possible. How could the `clock` package solve my problem in this case?

It seems important to me to give a solution to this because it breaks my workflow with Modeltime. Let me explain:

If I have a time series with dates as `real_ndex` (as I show in the first message) the problem is that when I try to use the `future_frame` function to extend my tibble it will not work and will give me an error. That means I have two options:

1. Extend the series manually.

2. Change the dates to make the future_frame function work (but I think this doesn't make much sense and also I don't think the users are very willing to go this way, but that's my opinion).

I think we need a simple solution for users for this situation.

**Comment by mdancho84** [comment] 2021-03-19 19:19
Yes, I think this can be improved. The problem is in `lubridate`, that it returns an `NA` when a date is not real. A simiple solution may be to take the previous date and `lubridate::rollforward()` or `rollbackward()`. A simple solution isn't usually so simple when date and datetimes are involved. Meaning we really need to think about any changes as they can break a lot of things.

**Comment by mdancho84** [comment] 2021-03-31 15:51
This is what we should look at for invalid dates. https://www.tidyverse.org/blog/2021/03/clock-0-1-0/

**Comment by mdancho84** [comment] 2021-11-14 18:17
This should be fixed now. I have included upgrades to:

- `tk_make_timeseries()`: Now detects if a date is on the end of the month and adjusts the series accordingly.
- `tk_make_future_timeseries()`: Now detects if all idx values are on end of the month, and adjusts the future series accordingly.

**Closed by mdancho84** 2021-11-14 18:17 UTC

**Comment by mdancho84** [comment] 2021-11-14 18:19
``` r
library(tidyverse)
library(timetk)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

series <- c("2011-01-31", "2011-04-30", "2011-07-31", "2011-10-31") %>% ymd()

tk_make_future_timeseries(series, length_out = 4)
#> [1] "2012-01-31" "2012-04-30" "2012-07-31" "2012-10-31"
```

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mdancho84** [comment] 2021-11-14 18:20
``` r
library(timetk)

timetk::tk_make_timeseries(start_date = '2011-09-30', end_date = '2018-12-31', by = 'quarter')
#>  [1] "2011-09-30" "2011-12-31" "2012-03-31" "2012-06-30" "2012-09-30"
#>  [6] "2012-12-31" "2013-03-31" "2013-06-30" "2013-09-30" "2013-12-31"
#> [11] "2014-03-31" "2014-06-30" "2014-09-30" "2014-12-31" "2015-03-31"
#> [16] "2015-06-30" "2015-09-30" "2015-12-31" "2016-03-31" "2016-06-30"
#> [21] "2016-09-30" "2016-12-31" "2017-03-31" "2017-06-30" "2017-09-30"
#> [26] "2017-12-31" "2018-03-31" "2018-06-30" "2018-09-30" "2018-12-31"
```

<sup>Created on 2021-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
